version: 1

services:
  - name: journaling-app
    source:
      type: docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    restart_policy: unless_stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
